import Card from "@/components/Card";
import { Container } from "@mui/material";
import Grid from "@mui/material/Unstable_Grid2";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bens Cool App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: "32px" }}>
        <Container maxWidth="lg">
          <Grid container spacing={3}>
            {[...Array(10)].map((_, i) => (
              <Grid xs={12} sm={6} md={3}>
                <Card />
              </Grid>
            ))}
          </Grid>
        </Container>
      </main>
    </>
  );
}
